apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backendsvc
  template:
    metadata:
      labels:
        app: backendsvc
    spec:
      containers:
        - name: backend
          image: kanwarsaad/backend:v2
          env:
            - name: MONGODB_URI
              value: "mongodb://kanwar-sikandar-ali-todo:mukarram1361@mongo-service:27017"
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000
