apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontendsvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: LoadBalancer
